package:
    name: lpsolve
    version: "5.5.2.3"

source:
    fn: lp_solve_5.5.2.3_source.tar.gz
    url: https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.3/lp_solve_5.5.2.3_source.tar.gz
    sha256: fb43ae8ad3bb4cee617863f7fc03b26ccc0ff7946a9cc4665cb9afa04c0a1cab

build:
    number: 4

test:
  files:
    - demo.c

about:
    home: http://lpsolve.sourceforge.net/5.5/
    license: LGPL

extra:
    recipe-maintainers:
        - snorfalorpagus
